[package]
name = "wopi"
version = "0.1.0"
authors = ["T. Jameson Little <t.jameson.little@gmail.com>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"

serde = "1"
serde_derive = "1"
